### ISSUE TITLE
python3 grpcio dependency

### ISSUE THREAD

**Issue by manuel-delverme** [dgraph-io/pydgraph#10]
pip3 tries to install a non python3 compatible version of prpcio

``` python
pip3 install --pre grpcio
pip3 install --no-deps pydgraph
```

fixed the problem

**Comment by manishrjain** [comment]
@mohitranka Could you please update the wiki if this will happen for all the users of pydgraph? Or, ensure that pip3 can pick up the right deps automatically?

**Comment by lazharichir** [comment]
Hi guys, definitely still happening. i have grpcio 1.x installed but pydgraph requires an older version that cannot be installed with python3x. Any idea when would that be fixed as all my app is in Python 3.5, soon 3.6.

**Comment by InfinityMod** [comment]
Hy,
I fixed the issue to work with python 3.x and the newest grpcio, you can find the repo in the pull requests yet.

The fix is for the current development release of dgraph. You can backport it to dgraph-io 0.74 by changing '/graphp.Dgraph/Run' to '/graph.Dgraph/Run' in the "graphresponse_pb2.py" file.

**Comment by gpahal** [comment]
Should be fixed by https://github.com/dgraph-io/pydgraph/pull/21

**Comment by gpahal** [comment]
Pull request merged to master.
