### ISSUE TITLE
What is the purpose of the any client function in client.py ?

### ISSUE THREAD

**Issue by shravan-v** [dgraph-io/pydgraph#129]
https://github.com/dgraph-io/pydgraph/blob/748339f749e7f14cf982804e89ecc893ad4ae9ac/pydgraph/client.py#L93

It would be helpful if the usage of this function is elaborated with an example.

**Comment by martinmr** [comment]
The client can be given multiple gRPC clients. This function is used to load balance the requests. I updated the documentation to hopefully make this clearer. I am not adding an example because this is not meant to be used by users. When you call any of the other methods (login, alter, etc), this method will automatically select a random gRPC client for you.
